import type { Metadata } from 'next'
import { brand } from '@/content/brand'
import { getDictionary } from '@/content/dictionaries'
import { defaultLocale, localePath, localeTags, locales, type Locale } from '@/i18n/config'

/**
 * hreflang, built once instead of on eight pages.
 *
 * Every page exists at three addresses and search engines have to be told that
 * they are the same page in different languages — otherwise the three compete
 * with each other for the same query and the wrong one wins. `x-default`
 * points at the locale an unprefixed URL redirects to, which is what a crawler
 * should show a visitor whose language we do not publish.
 */
export function alternatesFor(locale: Locale, path: string): Metadata['alternates'] {
  const languages: Record<string, string> = {
    'x-default': localePath(defaultLocale, path),
  }
  for (const l of locales) languages[localeTags[l]] = localePath(l, path)
  return { canonical: localePath(locale, path), languages }
}

/** The absolute URL of a page, for OpenGraph. `metadataBase` covers the rest. */
export function absoluteUrl(locale: Locale, path: string): string {
  return `https://${brand.domain}${localePath(locale, path)}`
}

/**
 * Canonical + hreflang + a COMPLETE OpenGraph block for one page.
 *
 * ⚠️ `openGraph` DOES NOT DEEP-MERGE ACROSS SEGMENTS. Next replaces the whole
 * object when a page defines one, so a page that sets `openGraph: { url }` and
 * expects to inherit `siteName`, `locale`, `type` and the auto-attached
 * `og:image` from the layout silently loses all four — including the image,
 * which the file convention only injects where nothing overrode the block.
 * That was found by grepping the built HTML, not by reading the code: the
 * failure is invisible until someone pastes a link into Slack.
 *
 * So this returns the whole block, every time, image included. A page that
 * wants its own social title passes one in; everything else stays correct by
 * construction.
 */
export function pageLocation(
  locale: Locale,
  path: string,
  overrides?: { title?: string; description?: string },
): Metadata {
  const t = getDictionary(locale)
  return {
    alternates: alternatesFor(locale, path),
    openGraph: {
      type: 'website',
      siteName: brand.name,
      locale: localeTags[locale].replace('-', '_'),
      url: absoluteUrl(locale, path),
      title: overrides?.title ?? `${brand.name} — ${t.site.tagline}`,
      description: overrides?.description ?? t.site.description,
      // The card generated by app/[locale]/opengraph-image.tsx, named
      // explicitly because the block above suppresses the automatic injection.
      images: [
        {
          url: localePath(locale, '/opengraph-image'),
          width: 1200,
          height: 630,
          alt: `${brand.name} — ${t.site.tagline}`,
        },
      ],
    },
  }
}
